import XCTest
@testable import Canto

// These run against the real app bundle (TEST_HOST), so they catch a sprite
// that fell out of project.yml's resources, not just a bad name mapping.
final class SpriteArtTests: XCTestCase {
    func test_everyShippedSpriteLoadsFromTheBundle() {
        let names = [
            "bear", "coffee", "crocodile", "dolphin", "eating", "elephant",
            "giraffe", "lion", "monkey", "tiger",
            "enemy-slime", "enemy-bat", "boss-dragon",
            "enemy-mushroom", "enemy-snail", "boss-wolf",
            "enemy-cactus", "enemy-scorpion", "boss-mummy",
            // Sprite corpus slice 1 (ranks 1–50, deduped, can/office/body swapped
            // for camera/fire/ice).
            "man", "house", "car", "dog", "horse", "tree", "boat", "gun",
            "girl", "guy", "boy", "men", "mother", "father", "baby", "doctor",
            "police", "bed", "room", "face", "phone", "hair", "school", "sit",
            "door", "head", "book", "night", "honey", "blood", "drink", "money",
            "paper", "hotel", "eye", "table", "plane", "dress", "food", "bag",
            "suit", "neck", "clock", "rock", "watch", "box", "camera", "fire", "ice",
            // Sprite corpus slices 2-3 (gated: body-parts, abstracts, alcohol dropped).
            "smoke", "card", "cup", "town", "street", "kid", "window", "bird",
            "church", "rain", "teeth", "bridge", "ring", "pig", "woman", "wall",
            "hat", "professor", "train", "coat", "saw", "truck", "shirt", "cat",
            "clothes", "bottle", "rose", "pizza", "magazine", "island", "jail",
            "bell", "mouth", "sun", "pants", "milk", "heart", "meat", "hill",
            "glass", "shoe", "toilet", "chicken", "doll", "hospital", "toast",
            "apple", "sea", "map", "garage", "park", "snake", "cow", "airport",
            "lake", "bug", "lawyer",
            // Sprite corpus slices 4-20 (gated; weapons dropped).
            "mule", "pumpkin", "fridge", "bean", "flag", "helmet", "sailor", "pan",
            "bracelet", "garbage", "spoon", "palm", "ketchup", "balloon", "bee", "sock",
            "shovel", "nest", "flashlight", "spaghetti", "tomato", "robe", "refrigerator", "chocolate",
            "jar", "necklace", "jump", "wolf", "motorcycle", "hamburger", "tower", "oven",
            "bacon", "towel", "peanut", "umbrella", "chair", "ham", "envelope", "soup",
            "fence", "drum", "shark", "banana", "passport", "cheese", "clown", "guitar",
            "carpet", "wallet", "pot", "fan", "ambulance", "whale", "priest", "ladder",
            "mail", "plate", "popcorn", "bush", "gift", "spider", "sheep", "planet",
            "trash", "grandmother", "potato", "toad", "barrel", "fork", "lipstick", "dice",
            "goose", "strawberry", "leopard", "cowboy", "leaf", "luggage", "sweater", "cabinet",
            "bat", "cage", "star", "bread", "cake", "boots", "basketball", "sleep",
            "castle", "pen", "turtle", "candy", "rope", "mask", "picture", "bath",
            "piano", "rabbit", "salad", "hook", "tea", "wheel", "sandwich", "turkey",
            "nail", "baseball", "duck", "blanket", "diamond", "lemon", "bowl", "corn",
            "frog", "lock", "suitcase", "cave", "eagle", "pillow", "princess", "lamp",
            "badge", "soap", "soldier", "razor", "elk", "bathtub", "shorts", "mailbox",
            "owl", "peach", "bicycle", "butterfly", "grape", "violin", "lobster", "vase",
            "toothbrush", "tuna", "orange", "gorilla", "moose", "peanuts", "cracker", "brick",
            "olive", "deer", "queen", "trophy", "bride", "briefcase", "sausage", "wheelchair",
            "hose", "ginger", "skirt", "carrot", "sofa", "tractor", "camel", "garlic",
            "sushi", "locker", "drawers", "shrimp", "rocket", "doughnut", "wheat", "scissors",
            "pyramid", "squirrel", "freezer", "helicopter", "ant", "singer", "cockroach", "chain",
            "drums", "salmon", "palace", "camp", "toothpaste", "lighthouse", "marbles", "robot",
            "microscope", "lasagna", "muffin", "cola", "blueberry", "platter", "flute", "pancake",
            "grandpa", "cradle", "grapefruit", "cheesecake", "pineapple", "octopus", "skunk", "meatball",
            "cupcake", "dove", "notebook", "fern", "bible", "mustache", "photographer", "museum",
            "bagel", "backpack", "coyote", "postcard", "waiter", "lettuce", "meteor", "telescope",
            "sled", "chili", "pope", "cactus", "laptop", "submarine", "penguin",
            // Sprite corpus slices 15, 17-20 (gated; tomb/thief dropped).
            "tub", "tray", "pea", "warehouse", "toaster", "cherry", "fountain", "crystal",
            "shop", "bookstore", "biscuit", "stadium", "wig", "grill", "cheeseburger", "kite",
            "king", "scooter", "earring", "onion", "pasta", "twins", "net", "emerald",
            "panther", "typewriter", "thermometer", "chopsticks", "nut", "brush", "coconut", "shield",
            "loaf", "plum", "pajamas", "omelet", "throne", "speaker", "torch", "saxophone",
            "blender", "raven", "mango", "bakery", "cranberry", "pigeon", "screwdriver", "oyster",
            "cello", "fiddle", "ski", "goggles", "bin", "weasel", "classroom", "jaguar",
            "iceberg", "orchid", "farmer", "cloud", "lollipop", "apron", "bowling", "pirate",
            "bandage", "pelican", "stocking", "pepper", "softball", "raspberry", "fortress", "janitor",
            "watermelon", "harp", "zebra", "dragonfly", "circus", "keyboard", "zipper", "disc",
            "scorpion", "escalator", "calendar", "mackerel", "fisherman", "astronaut", "snail",
            // Sprite corpus slice 21 (gated; synonyms and shared concepts aliased).
            "broccoli", "kangaroo", "seagull", "sculpture", "fireman", "pier", "curry",
            "goldfish", "parachute", "popsicle", "rainbow", "lizard", "checkers", "beaver",
            "scanner", "hamster", "holly", "lever", "squash",
            // Sprite corpus slice 22 (gated; synonyms and shared concepts aliased).
            "mast", "stereo", "walrus", "cappuccino", "harmonica", "heater", "weeds",
            "rudder", "firewood", "pistachio", "clarinet", "rag", "puppet", "volcano",
            "dishwasher", "saucer", "mosquito", "fig", "jellyfish", "tennis", "seaweed",
            "carousel", "reef", "ink", "banjo",
            // Sprite corpus slice 23 (gated; alcohol/drug/profanity/anatomy rows dropped).
            "hippo", "vinegar", "dial", "spray", "feed", "fishing", "date", "snowball",
            "chimpanzee", "buffet", "cricket", "shampoo", "bouquet", "necktie", "ledge",
            "pick", "canteen", "caviar", "groom", "cuff", "fossil", "slug", "aquarium",
            "mistletoe", "propeller",
            // Sprite corpus slices 24-45 (batch 1 fan-out; kid-safe culls applied).
            "accordion", "accountant", "acorn", "admiral", "airship", "albatross",
            "almond", "amber", "angel", "antenna", "anthill", "anvil", "apricot", "ark",
            "armchair", "asparagus", "asteroid", "athlete", "attendant", "auditorium",
            "auntie", "author", "avocado", "babysitter", "backboard", "bagpipes", "bait",
            "banister", "barber", "baron", "barracuda", "barricade", "baton", "batter",
            "battleship", "bead", "beanbag", "beanie", "beefsteak", "beehive", "beret",
            "bib", "billboard", "binder", "birdbath", "birdhouse", "bishop",
            "blackberry", "blackboard", "bleach", "blindfold", "blizzard", "blowtorch",
            "blueprint", "boatman", "bobcat", "bookcase", "bookkeeper", "bookmark",
            "bookshelf", "boomerang", "boxer", "bridesmaid", "brochure", "broomstick",
            "bugler", "bulldozer", "bullfrog", "bumblebee", "bungalow", "buoy",
            "businessman", "buttercup", "buyer", "buzzer", "caboose", "calculator",
            "calves", "camcorder", "canary", "candlestick", "cantaloupe", "capsule",
            "caramel", "carburetor", "cardigan", "cartridge", "casserole", "catcher",
            "caterpillar", "catfish", "cauliflower", "celery", "centipede", "chainsaw",
            "chameleon", "charcoal", "chauffeur", "cheetah", "chef", "chestnut",
            "chipmunk", "choir", "chute", "clinic", "clothesline", "clover", "clubhouse",
            "coach", "coaster", "cobbler", "cocoon", "cod", "comet", "compass",
            "convertible", "cookbook", "corkscrew", "cornflakes", "corral", "cougar",
            "courier", "crank", "crater", "crayon", "croissant", "crossroads",
            "crossword", "crowbar", "cry", "cube", "cuckoo", "custard", "cymbals",
            "daffodil", "dandelion", "darts", "dashboard", "detergent", "dictionary",
            "director", "ditch", "diver", "dome", "domino", "dominoes", "doormat",
            "drainpipe", "drawbridge", "dressing", "drill", "drummer", "drumstick",
            "dumpling", "dunk", "dustpan", "easel", "editor", "eel", "elf", "emu",
            "encyclopedia", "eraser", "eucalyptus", "extinguisher", "eyeglasses",
            "eyeliner", "fabric", "fairy", "farmhouse", "farmland", "fax", "fender",
            "firefly", "flagpole", "flamingo", "flare", "flask", "florist", "fondue",
            "foreman", "forklift", "frisbee", "frosting", "fuse", "gardener", "gavel",
            "gazebo", "gazelle", "geisha", "gel", "gelatin", "generator", "gerbil",
            "gingerbread", "glacier", "globe", "goatee", "gondola", "governor",
            "graffiti", "grandson", "grasshopper", "greenhouse", "guard", "gymnasium",
            "gymnast", "hail", "hairdryer", "hairnet", "hairpin", "hairspray", "hammock",
            "handprint", "hangar", "hanger", "haystack", "headband", "headlight",
            "headphones", "headset", "hedgehog", "herb", "herring", "hilltop", "hive",
            "hockey", "hoe", "horseradish", "hourglass", "housekeeper", "housewife",
            "hula", "hummingbird", "hydrant", "hyena", "icicle", "icing", "iguana",
            "incinerator", "incubator", "inhaler", "intercom", "investigator",
            "jackhammer", "jade", "jasmine", "jigsaw", "jockey", "jogging", "kale",
            "kennel", "keyhole", "kicking", "kiln", "kilt", "kiwi", "kneel", "koala",
            "kumquat", "laboratory", "ladybug", "lasso", "latte", "lavender",
            "lawnmower", "leeches", "leek", "librarian", "lice", "licorice", "lilac",
            "limousine", "llama", "locket", "locust", "magician", "magnet", "magnolia",
            "mailman", "mallet", "manager", "manhole", "mantis", "mantle", "manual",
            "maple", "marmalade", "marshmallow", "mascara", "maze", "mechanic",
            "medallion", "memo", "mermaid", "microchip", "microwave", "milkshake",
            "mink", "mint", "mitten", "molasses", "mongoose", "monk", "monument", "moth",
            "motorboat", "mousetrap", "mousse", "mouthwash", "muffler", "mullet",
            "mural", "musician", "muskrat", "muzzle", "nanny", "newsstand", "noodle",
            "nutmeg", "oar", "oat", "okra", "optometrist", "orangutan", "oregano",
            "ostrich", "otter", "overalls", "pager", "paintbrush", "painter", "pamphlet",
            "panda", "papaya", "paperboy", "paramedic", "paratrooper", "parsley",
            "pawnshop", "payphone", "peninsula", "penthouse", "periscope", "pharaoh",
            "pheasant", "phonograph", "pianist", "pickle", "pickup", "pilgrim", "pillar",
            "pillowcase", "pine", "pipeline", "piranha", "piston", "plumber", "plunger",
            "plywood", "podium", "poet", "porcupine", "porridge", "postman", "potion",
            "pottery", "printer", "prisoner", "projector", "puck", "puddle", "pug",
            "pump", "punching", "quail", "quarterback", "raccoon", "radish", "railway",
            "ramp", "receipts", "recorder", "referee", "reindeer", "reins", "rhinoceros",
            "rhubarb", "rink", "roadblock", "rod", "rodent", "rolling", "rooftop",
            "rosary", "salute", "samurai", "sandbox", "sandpaper", "sap", "sapphire",
            "sardine", "sash", "sauna", "sax", "scales", "scarecrow", "scientist",
            "scone", "scrapbook", "seesaw", "sesame", "sewer", "sewing", "shake",
            "shaved", "sherbet", "shipyard", "shoelace", "shrine", "shrubbery",
            "sidecar", "signal", "silicon", "siren", "skate", "skateboard", "skiing",
            "skylight", "skyscraper", "slate", "sledgehammer", "slime", "sling", "sloth",
            "snowboard", "snowflake", "snowman", "snowplow", "somersault", "soybean",
            "spacecraft", "spaceship", "sparks", "speedboat", "sphinx", "spinach",
            "spindle", "splint", "spotlight", "spring", "sprinkler", "spy", "squid",
            "staircase", "stake", "stall", "starfish", "stethoscope", "sticker",
            "stopwatch", "stream", "streetcar", "streetlight", "stretcher", "stroller",
            "stump", "sundae", "sunflower", "sunscreen", "supermarket", "suspenders",
            "swimsuit", "switchboard", "swordfish", "syringe", "tablecloth", "tadpole",
            "taillight", "talon", "tambourine", "tangerine", "tanker", "tap",
            "tarantula", "target", "taxicab", "teapot", "teriyaki", "termite", "thermos",
            "thermostat", "thimble", "thunder", "thunderstorm", "thyme", "tightrope",
            "tights", "tile", "tinfoil", "tinsel", "toffee", "token", "toolbox",
            "toothpick", "tornado", "tortilla", "tourist", "townhouse", "trainer",
            "trampoline", "transcript", "transmitter", "trapeze", "treadmill",
            "triangle", "tripod", "trolley", "trombone", "trunks", "tuba", "tugboat",
            "turnip", "turpentine", "turtleneck", "twig", "undershirt", "unicycle",
            "vaccine", "vacuum", "valet", "veil", "vest", "vet", "volleyball", "vote",
            "vulture", "waffle", "wallpaper", "wand", "warden", "warthog", "washer",
            "watchman", "welder", "wharf", "wheelbarrow", "wildcat", "windmill",
            "wizard", "wolverine", "woodpecker", "wreath", "wrestling", "yak",
            "yearbook", "yoga", "yoke", "zucchini",
            // Slices 46-67 (batch 2 fan-out).
            "aardvark", "acrobat", "alfalfa", "aloe", "alpaca", "amplifier", "analyst",
            "anchovy", "antibiotic", "antler", "archaeologist", "armband", "armrest",
            "artichoke", "assignment", "auctioneer", "avalanche", "aviator", "awning",
            "backgammon", "badger", "badminton", "baguette", "ballet", "bankbook",
            "barbell", "barometer", "bassoon", "bathhouse", "beaker", "beautician",
            "bedbug", "beet", "bellboy", "billiard", "billiards", "bingo", "birdcage",
            "bison", "blacksmith", "blowfish", "bouncer", "boutique", "bowler", "bowtie",
            "braid", "breadfruit", "breastplate", "brisket", "brooch", "brook",
            "buckwheat", "buggy", "bungee", "burlap", "bury", "bust", "cabbie", "caddie",
            "cadet", "camisole", "candelabra", "caravan", "carp", "cartwheel", "cashew",
            "cavalry", "ceramics", "chamomile", "champion", "charger", "chemist",
            "chessboard", "chime", "chrysanthemum", "cilantro", "clapping", "cleanser",
            "climbing", "clipper", "cloakroom", "cobblestone", "cobweb", "cockatoo",
            "cockpit", "comedian", "comic", "commentator", "compost", "conditioner",
            "conductor", "constellation", "contestant", "contractor", "controller",
            "cooler", "copperhead", "coral", "corsage", "corset", "coveralls", "cowhide",
            "crankshaft", "crepe", "crochet", "croquet", "crucifix", "cruise", "crutch",
            "cutlet", "cyclist", "dachshund", "daybreak", "denture", "dewdrop", "dike",
            "dogwood", "dressmaker", "dumbbell", "dummy", "dune", "dungeon", "earthquake",
            "earthworm", "earwig", "eggshell", "electrician", "embassy", "entertainer",
            "eyedropper", "faucet", "fencing", "fiddler", "figurine", "fillet", "fishnet",
            "flagstone", "flashing", "flooding", "flowerpot", "flyer", "flypaper",
            "flyswatter", "foil", "footsteps", "footstool", "foxhole", "freighter",
            "fryer", "gasket", "geologist", "geranium", "ginseng", "glider", "goalie",
            "goalkeeper", "goblet", "goldsmith", "gooseberry", "gramophone", "grin",
            "grindstone", "guava", "guitarist", "hailstorm", "handball", "handbrake",
            "harpsichord", "headboard", "headdress", "headmaster", "hearth", "hermit",
            "hickory", "highlighter", "hike", "hinge", "hippie", "hobbit", "hologram",
            "honeydew", "hovercraft", "hubcap", "hugging", "hyacinth", "ibuprofen",
            "insecticide", "interviewer", "investor", "iodine", "jackal", "jogger",
            "joystick", "judo", "juggling", "juicer", "juror", "kaleidoscope", "karate",
            "kayak", "kickboxing", "kimono", "kingfisher", "knitting", "lamppost",
            "lampshade", "landlady", "lapel", "lark", "ledger", "leech", "leggings",
            "lifeboat", "lifeguard", "limestone", "locksmith", "loincloth",
            "longshoreman", "lookout", "loom", "loon", "lotus", "lounge", "lubricant",
            "lunchbox", "macaw", "mailbag", "manatee", "mandolin", "margarine", "mascot",
            "matchbox", "mathematician", "megaphone", "meteorite", "microfilm", "midwife",
            "mimosa", "miner", "minibus", "minnow", "mite", "moisturizer", "monster",
            "motorcyclist", "mulberry", "multivitamin", "mussel", "nectarine", "neon",
            "ninja", "notepad", "nudge", "nugget", "oasis", "observatory", "odometer",
            "onyx", "opal", "opossum", "ore", "origami", "outlet", "pacifier", "pageant",
            "pallet", "paperweight", "parasite", "parchment", "parfait", "parsnip",
            "partridge", "peddler", "pedestrian", "peephole", "pennant", "peppermint",
            "performer", "pesticide", "pesto", "physicist", "pickaxe", "pike", "pinball",
            "pincushion", "planetarium", "poinsettia", "politician", "pomegranate",
            "pontoon", "postage", "propane", "pulley", "pushup", "quartet", "rafter",
            "raindrop", "rainforest", "rainwater", "ratchet", "receptionist", "recliner",
            "recording", "rectangle", "repairman", "rickshaw", "riverbank", "rivet",
            "rugby", "saffron", "salamander", "sandal", "sandalwood", "sandcastle",
            "sandstone", "sandstorm", "sauerkraut", "scaffold", "scaffolding", "scallion",
            "scrambled", "scroll", "scuba", "seaplane", "searchlight", "seashore",
            "shellfish", "shoehorn", "showerhead", "shredder", "sirloin", "skateboarder",
            "slipknot", "smokestack", "smoothie", "snapper", "snore", "snorkel",
            "snowdrift", "snowmobile", "soak", "socket", "spacesuit", "spareribs",
            "speedometer", "splashing", "sportswear", "squint", "squire", "stable",
            "stapler", "steakhouse", "steamroller", "steeple", "steering", "stegosaurus",
            "stencil", "stewardess", "stink", "stirrup", "stockade", "stockbroker",
            "stocks", "strongbox", "stuffed", "stuntman", "sturgeon", "sucker",
            "sugarcane", "sundial", "sunlamp", "sunroom", "superglue", "supermodel",
            "surfboard", "swab", "swallow", "synagogue", "tango", "tapestry", "tapioca",
            "tassel", "teakettle", "teardrop", "technician", "teller", "thesaurus",
            "thistle", "thumbprint", "thumbtack", "toadstool", "tollbooth", "tonic",
            "topaz", "tortellini", "trapdoor", "tricycle", "trough", "truffle", "turbine",
            "turntable", "turquoise", "tusk", "typist", "tyrannosaurus", "ukulele",
            "urinal", "ventriloquist", "vinyl", "visor", "wafer", "wasabi", "washboard",
            "watchtower", "whetstone", "whimper", "whirlpool", "whistling", "whitefish",
            "wicker", "wildfire", "winch", "wiper", "workbench", "workstation",
            "wormwood", "xylophone", "yank", "yolk",
            // Slices 68-89 (batch 3 fan-out).
            "abacus", "aerosol", "alchemist", "alien", "amulet", "anemone", "antacid",
            "anthropologist", "aphid", "architect", "archives", "armada", "armoire",
            "astronomer", "azalea", "backpacker", "barista", "bedroll", "biologist",
            "bloomers", "blower", "bonsai", "breaker", "breaststroke", "bricklayer",
            "broadcaster", "builder", "bullion", "calipers", "carnation", "cellist",
            "centrifuge", "ceramic", "chairperson", "chinaware", "chum", "clamshell",
            "cleaner", "clipping", "clothespin", "clutch", "coachman", "coastguard",
            "cogwheel", "compactor", "companion", "compressor", "convent", "conveyor",
            "cornucopia", "craftsman", "critic", "curling", "curtsy", "cuttlefish",
            "designer", "desktop", "disco", "dispenser", "dossier", "drone", "druggist",
            "duplex", "earmuff", "earplug", "eatery", "educator", "ember", "enamel",
            "euro", "explorer", "expressway", "eyepiece", "faceplate", "filament",
            "firework", "fisherwoman", "fishpond", "fjord", "flatbed", "flee", "flipper",
            "floppy", "flounder", "flowerbed", "foggy", "footboard", "footman", "fritter",
            "gangway", "gardening", "gatekeeper", "gazette", "gemstone", "giggling",
            "gloss", "grater", "grenadine", "grinder", "grocer", "groomsman", "guinea",
            "gyroscope", "handcart", "handstand", "harvester", "hazelnut", "helmsman",
            "heron", "hexagon", "hibiscus", "historian", "honeysuckle", "hopscotch",
            "hothouse", "hub", "icehouse", "inventor", "jerky", "kneepad", "lanyard",
            "laryngoscope", "lectern", "lemongrass", "lentil", "lifebuoy", "lionfish",
            "lozenge", "magistrate", "mallard", "mammoth", "masseur", "mentor",
            "meteorologist", "metronome", "millionaire", "missionary", "monorail",
            "mothball", "motherboard", "mutton", "nameplate", "navigator", "nebula",
            "neurologist", "nodding", "nougat", "oboe", "octagon", "opener", "oriole",
            "oscilloscope", "oval", "palette", "pansy", "parliament", "passkey",
            "pathologist", "pawn", "pedometer", "perch", "persimmon", "pew",
            "philosopher", "photocopier", "pigsty", "pilaf", "pinwheel", "platypus",
            "plough", "plume", "pointer", "postmark", "primrose", "processor",
            "programmer", "prophet", "pterodactyl", "radiometer", "receiver", "reflector",
            "rouge", "router", "sachet", "safflower", "salesperson", "samba", "sandpiper",
            "sapling", "sarong", "sawhorse", "scallop", "schnauzer", "schoolmate",
            "scorekeeper", "sculptor", "seaport", "sextant", "shaker", "shallot",
            "shopkeeper", "shrug", "sideboard", "silkworm", "silverfish", "skullcap",
            "smiley", "solarium", "solicitor", "sonar", "sorbet", "spam", "spawn",
            "spectator", "spectrometer", "spokesman", "spreadsheet", "sprint",
            "stonemason", "storyboard", "strainer", "striker", "swarm", "synthesizer",
            "tabloid", "takeout", "talisman", "teabag", "teammate", "tenderloin",
            "tentacle", "tiptoe", "titan", "toner", "totem", "toucan", "translator",
            "trio", "turbojet", "turnstile", "ultrasound", "urchin", "ventilator",
            "villager", "washbasin", "washbowl", "weightlifting", "welding", "wetsuit",
            "whipping", "wildflower", "windbreaker", "wombat", "woodcutter", "worksheet",
            "wring", "yawning", "yellowtail", "zookeeper", "zoologist",
            // Slices 90-112 (batch 4 fan-out).
            "aerobics", "airmail", "amoeba", "antiseptic", "apothecary", "arched",
            "archipelago", "archive", "astrologer", "astrologist", "awl", "backbend",
            "backrest", "balsam", "bazaar", "beech", "bloodworm", "bodybuilding",
            "bookend", "bookworm", "botanist", "bouillon", "breakwater", "bunting",
            "calligrapher", "capacitor", "capsize", "cascade", "centaur", "clapper",
            "coffer", "colander", "colonist", "conduit", "connector", "conqueror",
            "copyist", "cowl", "crisps", "croaker", "culvert", "cumulus", "curator",
            "cursor", "decoder", "demonstrator", "developer", "dipstick", "dowel",
            "drapery", "drier", "drifter", "duckweed", "ecologist", "edifice",
            "electromagnet", "elliptical", "environmentalist", "equestrian", "examiner",
            "excavator", "exporter", "extractor", "fingerboard", "fishmonger", "flatiron",
            "floodgate", "flyover", "geographer", "gnaw", "godson", "groundsheet",
            "gummy", "guru", "halter", "herdsman", "hexagonal", "hibachi", "hooter",
            "humidifier", "innkeeper", "insole", "keystone", "kindling", "knead",
            "laminator", "lawmaker", "linesman", "linguist", "litterbug", "lobbyist",
            "lynx", "magnifying", "manservant", "marmot", "measuring", "migrant",
            "millet", "millstone", "neckerchief", "nettle", "nobleman", "noonday",
            "notary", "nutritionist", "organizer", "oxtail", "pampers", "paragliding",
            "parallelogram", "pauper", "peony", "pilothouse", "pipette", "plaything",
            "poplar", "proofreader", "prospector", "protester", "protractor", "puffball",
            "pumice", "puncher", "purifier", "pusher", "reaper", "recline", "refuel",
            "registrar", "riveter", "rotor", "rowing", "sable", "sanitizer", "scraper",
            "seawall", "seismologist", "seismometer", "semicircle", "seminary", "settler",
            "shantytown", "shivering", "sidestep", "siphon", "sleepwalking", "soldering",
            "spherical", "spire", "springboard", "stalagmite", "stalk", "statistician",
            "steersman", "stilt", "stooping", "stowaway", "straightedge", "strongman",
            "sumo", "sunbath", "supernova", "surveyor", "tachometer", "tailcoat",
            "tempura", "tenement", "terracotta", "tester", "thermograph", "thrush",
            "torchbearer", "tradesman", "trapezoid", "triceratops", "tunic", "vagabond",
            "vane", "vaulting", "virologist", "vise", "waddling", "wader", "watercolor",
            "watercress", "waterwheel", "windsock", "windsurfing", "wingman", "woodblock",
            "yelp",
            // Plain batch 01 (plain-01.tsv).
            "ashes", "bank", "bike", "board", "butter", "cable", "can", "cement", "cloth",
            "cotton", "cream", "curtain", "dirt", "dough", "elevator", "fat", "gold",
            "handkerchief", "jelly", "kitchen", "leather", "lid", "mud", "mustard", "pin",
            "pocket", "pool", "pudding", "radio", "restaurant", "rug", "saddle", "salt",
            "sand", "sauce", "shower", "sponge", "statue", "steel", "sugar", "swamp",
            "theater", "tobacco", "trailer", "tunnel", "underwear", "wax",
            // Plain batch 02 (plain-02.tsv).
            "album", "altar", "bikini", "bolt", "braces", "brass", "brownie", "canvas",
            "cardboard", "cereal", "chalk", "checkbook", "cinnamon", "cocoa", "cork",
            "courtroom", "dam", "deodorant", "diploma", "dock", "doorstep", "drain",
            "drawer", "dust", "fluid", "foam", "fudge", "gasoline", "hay", "lace", "lava",
            "leash", "mat", "mayonnaise", "medication", "menu", "napkin", "oatmeal",
            "pantyhose", "pill", "pod", "pole", "shaft", "silk", "silver", "timber",
            "videotape", "yogurt",
            // Plain batch 03 (plain-03.tsv).
            "aluminum", "artist", "asphalt", "barbershop", "beetle", "beggar", "bra",
            "cabbage", "canister", "cardinal", "cologne", "crumb", "dumpster", "ferret",
            "garter", "giant", "gravel", "hairdresser", "hatch", "kerosene", "latex",
            "lighter", "linen", "marker", "nod", "pollen", "poster", "quicksand",
            "racetrack", "raisin", "roller", "runway", "rye", "sawdust", "shawl",
            "shuttle", "spa", "spandex", "stuffing", "tailor", "tar", "titanium", "tofu",
            "vanilla", "velvet", "waterfall",
            // Plain batch 03 flagged (gunpowder visible, morphine kid-mode-hidden).
            "gunpowder", "morphine",
            // Plain batch 04 (plain-04.tsv).
            "albino", "ammonia", "asbestos", "beeswax", "bran", "cellophane", "chemicals",
            "chlorine", "corduroy", "cumin", "denim", "dew", "doorstop", "fiber",
            "fiberglass", "flannel", "formaldehyde", "fuzz", "linoleum", "mahogany",
            "malt", "miniskirt", "nylon", "pacemaker", "pellet", "pink", "platinum",
            "putty", "saline", "saltwater", "seasoning", "serum", "sheepskin", "silt",
            "snakeskin", "sod", "steroids", "sulfur", "topsoil", "waistband", "yeast",
            // Plain batch 05 (plain-05.tsv).
            "acrylic", "buttonhole", "coolant", "cornstarch", "ethanol", "fluoride",
            "frankincense", "graphite", "helium", "indigo", "lacquer", "newsprint",
            "oxygen", "pigment", "pigtail", "polyester", "refugee", "rind", "runaway",
            "sackcloth", "sharkskin", "snuff", "stationery", "suede", "sweetener",
            "tiller", "tortoiseshell", "tramp", "whey", "wrapping",
            // Plain batch 06 (plain-06.tsv).
            "bicarbonate", "bristle", "cyan", "ebony", "filings", "floodwater",
            "groundwater", "oilpaper", "permafrost", "planner", "sealant", "slush",
            "spearhead", "stimulant", "talc", "veneer",
            // Plain batch 07 (plain-07.tsv).
            "polystyrene", "sepia", "soundproofing", "zigzag",
            // Flag batch 01 (flag-01.tsv).
            "alcohol", "arrow", "axe", "bar", "bartender", "beer", "bow", "cannon",
            "champagne", "cigar", "cigarette", "cocaine", "cocktail", "dagger",
            "detonator", "grenade", "keg", "missile", "pipe", "slingshot", "sword",
            "thief", "tomb", "wine",
            // Flag batch 02 (flag-02.tsv).
            "chisel", "cleaver", "club", "crossbow", "explode", "flamethrower", "harpoon",
            "lottery", "paintball", "poker", "sickle", "troll", "vampire", "werewolf",
            "zombie",
            // Flag batch 03 (flag-03.tsv).
            "clench", "executioner", "hookah", "horsewhip", "landmine", "landslide",
            "mahjong", "matador", "roulette", "sarcophagus", "shipwreck",
            "straightjacket", "trident", "tsunami",
            // Flag batch 04 (flag-04.tsv).
            "barbed", "blaster", "breathalyzer", "flail", "grille", "unicorn",
            // Anatomy batch 01 (anatomy-01.tsv) - shared body/head/hand base + highlight ring.
            "ankle", "arm", "bald", "beard", "body", "brain", "cheek", "chest", "claw",
            "elbow", "finger", "fist", "foot", "forehead", "heel", "jaw", "kidney",
            "knee", "knuckle", "knuckles", "limb", "lip", "liver", "lung", "muscle",
            "nose", "pelvis", "rib", "saliva", "scalp", "shoulder", "skull", "spit",
            "stomach", "sweat", "tattoo", "thigh", "throat", "tongue", "urine", "wing",
            "wound", "wrist",
            // anatomy-02.
            "antennae", "aorta", "armpit", "artery", "barefoot", "biceps", "bladder",
            "blister", "cuticle", "diarrhea", "drool", "earlobe", "eyebrow", "eyelash",
            "eyelid", "femur", "forearm", "freckles", "headquarters", "hip", "jawbone",
            "marrow", "navel", "nostril", "plankton", "rump", "snout", "spleen", "stitch",
            "tummy", "udder", "wart",
            // anatomy-03.
            "airway", "appendix", "bunion", "cartilage", "cheekbone", "clavicle",
            "cornea", "dimple", "earwax", "esophagus", "exoskeleton", "fibula",
            "fingertip", "gallbladder", "gills", "hairline", "hangnail", "kneecap",
            "mane", "manicure", "mucus", "pinkie", "shinbone", "sternum", "sunburn",
            "tartar", "thyroid", "tonsil",
            // anatomy-04 to 06.
            "asthma", "bacteria", "blackheads", "bloodshot", "blushing", "brainstem",
            "bucktooth", "capillary", "cerebellum", "cortex", "diaphragm", "earache",
            "eardrum", "flatfoot", "frown", "gallstone", "giblets", "gizzard", "gland",
            "gulping", "hamstring", "jowl", "ligament", "nape", "nosebleed", "palate",
            "perm", "phalanges", "phlegm", "pore", "retina", "scapula", "septum", "shank",
            "sinus", "smirk", "stamen", "stoma", "subcommittee", "swelling", "synapse",
            "tailbone", "thumbnail", "triceps", "ventricle", "vertebra",
            // One-offs.
            "dinosaur",
        ]
        for name in names {
            XCTAssertNotNil(SpriteArt.image(named: name), "\(name).png missing from the app bundle")
        }
    }

    func test_cardImage_matchesTheEnglishWordCaseInsensitively() {
        XCTAssertNotNil(SpriteArt.cardImage(forEnglish: "Bear"))
        XCTAssertNil(SpriteArt.cardImage(forEnglish: "honesty"))
    }

    // The dictionary's word is "eat"; the sprite drawn for it is "eating".
    func test_cardImage_resolvesTheEatAlias() {
        XCTAssertNotNil(SpriteArt.cardImage(forEnglish: "eat"))
    }

    // "eyes" was deduped into 眼's "eye" sprite at draw time; the alias keeps
    // an "eyes" card from showing a blank.
    func test_cardImage_resolvesTheEyesAlias() {
        XCTAssertNotNil(SpriteArt.cardImage(forEnglish: "eyes"))
    }

    // Plurals/synonyms resolve to an already-drawn sprite instead of a blank.
    func test_cardImage_resolvesTheSliceAliases() {
        XCTAssertNotNil(SpriteArt.cardImage(forEnglish: "ship"))   // -> boat
        XCTAssertNotNil(SpriteArt.cardImage(forEnglish: "mom"))    // -> mother
        XCTAssertNotNil(SpriteArt.cardImage(forEnglish: "cab"))    // -> car
        XCTAssertNotNil(SpriteArt.cardImage(forEnglish: "taxi"))   // -> car (cab has no sprite of its own)
        XCTAssertNotNil(SpriteArt.cardImage(forEnglish: "puppy"))  // -> dog
        XCTAssertNotNil(SpriteArt.cardImage(forEnglish: "dragon")) // -> boss-dragon
        XCTAssertNotNil(SpriteArt.cardImage(forEnglish: "rooster")) // -> chicken
        XCTAssertNotNil(SpriteArt.cardImage(forEnglish: "nightgown")) // -> pajamas
        XCTAssertNotNil(SpriteArt.cardImage(forEnglish: "trout")) // -> salmon
        XCTAssertNotNil(SpriteArt.cardImage(forEnglish: "mommy")) // -> mother
        XCTAssertNotNil(SpriteArt.cardImage(forEnglish: "chariot")) // -> car
        XCTAssertNotNil(SpriteArt.cardImage(forEnglish: "barbecue")) // -> grill
        XCTAssertNotNil(SpriteArt.cardImage(forEnglish: "snails")) // -> snail
        XCTAssertNotNil(SpriteArt.cardImage(forEnglish: "sailboat")) // -> boat
    }

    // Every enemy any biome can put on a floor must resolve to a sprite -
    // this is what keeps a new biome from shipping with a missing PNG.
    func test_enemyImage_mapsEveryBiomeEnemyToASprite() {
        for biome in Biome.allCases {
            for enemy in biome.fightEnemies + [biome.bossEnemy] {
                XCTAssertNotNil(SpriteArt.enemyImage(for: enemy), "\(enemy) has no sprite")
            }
        }
        XCTAssertNil(SpriteArt.enemyImage(for: "kraken"), "unknown enemies fall back to the SF Symbol")
    }
}
